# Default values for oidc-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
secret:
  name: oidc-config
  issuer: PLACEHOLDER
  upstream: http://localhost:80
  clientID: PLACEHOLDER
  clientSecret: PLACEHOLDER
  cookieSecret: PLACEHOLDER
  oidcScopes: "openid profile"
  env: {}

service:
  selector: {}
  name: oauth-proxy
  webPort: 4180
  metricsPort: 44180

users: {}