apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-executor
  labels:
    {{- include "test-base.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
  labels:
    {{- include "test-base.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.rbacRules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-role-binding
  labels:
    {{- include "test-base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-role
subjects:
  - kind: ServiceAccount
    name: argo-executor
    namespace: {{ .Release.Namespace }}
