apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ include "postgres.crd-name" . }}
  labels:
  {{ include "postgres.labels" . | nindent 4 }}
spec:
  teamId: {{ .Values.team }}
  volume:
    size: {{ .Values.storage.size }}
  numberOfInstances: {{ .Values.replicas }}
  users:
    {{ .Values.user }}:  # database owner
    - superuser
    - createdb
  {{ if .Values.resources }}
  resources:
  {{ mergeOverwrite .Values.default.resources .Values.resources | toYaml | nindent 4 }}
  {{ end }}
  databases:
    {{ .Values.user }}: {{ .Values.dbName }}  # dbname: owner
  postgresql:
    version: {{ .Values.version | quote }}
  sidecars:
  - image: gcr.io/pluralsh/postgres-exporter:0.8.0
    name: exporter
    ports:
    - containerPort: 9187
      name: http-metrics
      protocol: TCP
    env:
    - name: "DATA_SOURCE_URI"
      value: "127.0.0.1:5432/{{ .Values.dbName }}?sslmode=disable"
    - name: "DATA_SOURCE_USER"
      valueFrom:
        secretKeyRef:
          name: postgres.{{ include "postgres.crd-name" . }}.credentials.postgresql.acid.zalan.do
          key: username
    - name: "DATA_SOURCE_PASS"
      valueFrom:
        secretKeyRef:
          name: postgres.{{ include "postgres.crd-name" . }}.credentials.postgresql.acid.zalan.do
          key: password
