apiVersion: platform.plural.sh/v1alpha1
kind: Runbook
metadata:
  name: db-scaling
  labels:
    platform.plural.sh/pinned: 'true'
{{ include "postgres.labels" . | indent 4 }}
spec:
  name: Postgres Scaling
  description: overview of how to accurately scale {{ .Values.ownerChart }}'s postgres instance
  alerts:
  - name: {{ .Values.dbName }}PostgreSQLCpuHigh
  - name: {{ .Values.dbName }}PostgreSQLMemHigh
  display: |-
{{ .Files.Get "runbooks/db-scaling.xml" | indent 4 }}
  datasources:
  - name: cpu
    type: prometheus
    prometheus:
      format: cpu
      legend: $pod
      query: sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"{{ include "postgres.crd-name" . }}-[0-9]+"}[5m])) by (pod)
  - name: memory
    type: prometheus
    prometheus:
      format: memory
      legend: $pod
      query: sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"{{ include "postgres.crd-name" . }}-[0-9]+"}) by (pod)
  - name: volume
    type: prometheus
    prometheus:
      format: none
      legend: $persistentvolumeclaim
      query: (kubelet_volume_stats_capacity_bytes{namespace="{{ .Release.Namespace }}", persistentvolumeclaim=~"pgdata-{{ include "postgres.crd-name" . }}-.*"} - kubelet_volume_stats_available_bytes{namespace="{{ .Release.Namespace }}", persistentvolumeclaim=~"pgdata-{{ include "postgres.crd-name" . }}-.*"}) / kubelet_volume_stats_capacity_bytes{namespace="{{ .Release.Namespace }}", persistentvolumeclaim=~"pgdata-{{ include "postgres.crd-name" . }}-.*"}
  - name: statefulset
    type: kubernetes
    kubernetes:
      resource: statefulset
      name: {{ include "postgres.crd-name" . }}
  - name: nodes
    type: nodes
  actions:
  - name: scale
    action: config
    redirectTo: '/'
    configuration:
      updates:
      - path: 
        - {{ default .Release.Namespace .Values.ownerChart }}
        - postgres
        - resources
        - requests
        - cpu
        valueFrom: cpu
      - path:
        - {{ default .Release.Namespace .Values.ownerChart }}
        - postgres
        - resources
        - requests
        - memory
        valueFrom: memory
      - path: 
        - {{ default .Release.Namespace .Values.ownerChart }}
        - postgres
        - resources
        - limits
        - cpu
        valueFrom: cpu-limit
      - path:
        - {{ default .Release.Namespace .Values.ownerChart }}
        - postgres
        - resources
        - limits
        - memory
        valueFrom: memory-limit
      - path:
        - {{ default .Release.Namespace .Values.ownerChart }}
        - postgres
        - replicas
        valueFrom: replicas
      - path:
        - {{ default .Release.Namespace .Values.ownerChart }}
        - postgres
        - storage
        - size
        valueFrom: volume
