serviceAccount:
  annotations: {}

rbacRules:
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - get
  - watch
  - list

application: plural
promoteTag: stable
testName: plural-test

steps:
- name: watch
  description: it wait until the app crd is ready
  template:
    container:
      image: gcr.io/pluralsh/test-base:0.1.6
      args: ["{{ .Values.repository }}"]
