## postgres db metadata
team: plural
user: example
dbName: plural
ownerChart: null
suffix: ""
infix: ""

version: '13'

# scaling information

replicas: 1
storage:
  size: 25Gi
resources: {}
default:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: '2'
      memory: 1Gi