## postgres db metadata
team: plural
user: example
dbName: plural
ownerChart: null
suffix: ""
infix: "-postgres"

annotations: {}

version: '13'

clone: null

# scaling information

replicas: 1
storage:
  size: 25Gi
resources: {}
default:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: '2'
      memory: 1Gi

exporter:
  image:
    repository: dkr.plural.sh/postgres/prometheuscommunity/postgres-exporter
    tag: v0.11.1
  resources: {}
  default:
    resources:
      requests:
        cpu: 1m
        memory: 15Mi
      limits:
        memory: 20Mi
        cpu: 10m
