apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
  OAUTH2_PROXY_METRICS_ADDRESS: 0.0.0.0:44180
  OAUTH2_PROXY_COOKIE_EXPIRE: 48h
  OAUTH2_PROXY_COOKIE_REFRESH: 24h
  OAUTH2_PROXY_COOKIE_SECURE: "true"
  OAUTH2_PROXY_COOKIE_NAME: _oauth2_proxy
  OAUTH2_PROXY_COOKIE_SAMESITE: lax
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_OIDC_ISSUER_URL: {{ .Values.secret.issuer }}
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
  OAUTH2_PROXY_SCOPE: "openid profile"
  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
  OAUTH2_PROXY_UPSTREAMS: {{ .Values.secret.upstream }}
  OAUTH2_PROXY_USER_ID_CLAIM: email
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.secret.clientID }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.secret.clientSecret }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.secret.cookieSecret }}
  {{ range $key, $val := .Values.secret.env -}}
  {{ $key }}: {{ $val }}
  {{ end }}
  {{ if .Values.users }}
  OAUTH2_PROXY_HTPASSWD_FILE: /etc/plural/htpasswd.txt
  {{ end }}
{{ if .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: httpaswd-users
type: Opaque
stringData:
  htpasswd.txt: |
    {{ range $user, $pwd := .Values.users -}}
    {{ htpasswd $user $pwd }}
    {{ end }}
{{ end }}