{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "clickhouse.fullname" . }}-backup-script
data:
{{ (.Files.Glob "scripts/clickhouse_backup.sh").AsConfig | indent 2 }}
{{- end }}
