{{- if .Values.preDeleteInstallationHook.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "clickhouse.fullname" . }}-pre-delete-job
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
spec:
  template:
    spec:
      containers:
      - name: delete-clickhouse-installation
        image: {{ .Values.preDeleteInstallationHook.image.repository }}:{{ .Values.preDeleteInstallationHook.image.tag }}
        args:
        - delete
        - clickhouseinstallation
        - {{ template "clickhouse.fullname" . }}
        - --namespace
        - {{ .Release.Namespace }}
        - --wait
        - --timeout=600s
      restartPolicy: Never
      serviceAccountName: {{ include "clickhouse.fullname" . }}-pre-delete-job
  backoffLimit: 4
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "clickhouse.fullname" . }}-pre-delete-job
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "clickhouse.fullname" . }}-pre-delete-job
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
rules:
- apiGroups: ["clickhouse.altinity.com/v1"]
  resources: ["clickhouseinstallations"]
  verbs: ["delete","deletecollection","get","list","patch","create","update","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "clickhouse.fullname" . }}-pre-delete-job
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "1"
subjects:
- kind: ServiceAccount
  name: {{ include "clickhouse.fullname" . }}-pre-delete-job
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "clickhouse.fullname" . }}-pre-delete-job
  apiGroup: rbac.authorization.k8s.io
{{- end }}