apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clickhouse.fullname" . }}-{{ .Values.user }}-password
  labels:
  {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}
{{- if and .Values.backup.enabled .Values.backup.backup_password (not .Values.backup.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clickhouse.fullname" . }}-{{ .Values.backup.backup_user }}-password
  labels:
  {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.backup.backup_password | b64enc | quote }}
{{- end }}
