apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    role: alert-rules
  name: {{ .Values.dbName }}-rules
spec:
  groups:
  - name: {{ .Values.dbName }}
    rules:
    - alert: {{ .Values.dbName }}PostgresCpuHigh
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace="{{ .Release.Namespace }}",pod=~"{{ include "postgres.crd-name" . }}-[0-9]+"}[5m]))
          / sum(kube_pod_container_resource_requests{endpoint="http",namespace="{{ .Release.Namespace }}", pod=~"{{ include "postgres.crd-name" . }}-[0-9]+", resource="cpu"})
        )  > 0.6
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: {{ .Values.ownerChart }} dbs's cpu usage has gotten too high
        description: the cpu utilization of your plural {{ .Values.ownerChart }} is higher than recommended
    - alert: {{ .Values.dbName }}PostgresMemHigh
      expr: |
        (
          sum(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}",pod=~"{{ include "postgres.crd-name" . }}-[0-9]+",image!="",container!=""})
          / sum(kube_pod_container_resource_requests{endpoint="http",resource="memory",namespace="{{ .Release.Namespace }}", pod=~"{{ include "postgres.crd-name" . }}-[0-9]+"})
        )  > 1
      for: 5m
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: {{ .Values.ownerChart }} db's memory usage has gotten too high
        description: the memory utilization of your plural {{ .Values.ownerChart }} db is higher than recommended
