apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbName }}-master
  labels:
    spilo-role: master
    {{ include "postgres.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  selector:
    spilo-role: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbName }}-replica
  labels:
    spilo-role: replica
    {{ include "postgres.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  selector:
    spilo-role: replica